#!/bin/bash

#SBATCH -J myjob           # Job name
#SBATCH -o run_2o_32       #Name of stdout output file
#SBATCH -e run_2e_32      # Name of stdout output file
#SBATCH -p skx-normal      # Queue (partition) name
#SBATCH -N 1               # Total # of nodes (must be 1 for serial)
#SBATCH -n 1               # Total # of mpi tasks (should be 1 for serial)
#SBATCH -t 02:00:00        # Run time (hh:mm:ss)
#SBATCH -A CCR21003      # Allocation name (req'd if you have more than 1)

perf stat -e L1-dcache-loads:u,L1-dcache-load-misses:u,l2_rqsts.references:u,l2_rqsts.miss:u --repeat 20 ./matmul 32 -1 -1 -1
<<comment
perf stat -e ref-cycles:u,L1-dcache-loads:u,L1-dcache-load-misses:u,l2_rqsts.references:u,l2_rqsts.miss:u --repeat 20 ./matmul 32 -1 -1 -1
perf stat -e ref-cycles:u,L1-dcache-loads:u,L1-dcache-load-misses:u,l2_rqsts.references:u,l2_rqsts.miss:u --repeat 20 ./matmul 32 16 -1 -1
perf stat -e ref-cycles:u,L1-dcache-loads:u,L1-dcache-load-misses:u,l2_rqsts.references:u,l2_rqsts.miss:u --repeat 20 ./matmul 32 8 -1 -1
perf stat -e ref-cycles:u,L1-dcache-loads:u,L1-dcache-load-misses:u,l2_rqsts.references:u,l2_rqsts.miss:u --repeat 20 ./matmul 32 4 -1 -1
perf stat -e ref-cycles:u,L1-dcache-loads:u,L1-dcache-load-misses:u,l2_rqsts.references:u,l2_rqsts.miss:u --repeat 20 ./matmul 32 2 -1 -1
perf stat -e ref-cycles:u,L1-dcache-loads:u,L1-dcache-load-misses:u,l2_rqsts.references:u,l2_rqsts.miss:u --repeat 20 ./matmul 32 16 8 -1
perf stat -e ref-cycles:u,L1-dcache-loads:u,L1-dcache-load-misses:u,l2_rqsts.references:u,l2_rqsts.miss:u --repeat 20 ./matmul 32 16 4 -1
perf stat -e ref-cycles:u,L1-dcache-loads:u,L1-dcache-load-misses:u,l2_rqsts.references:u,l2_rqsts.miss:u --repeat 20 ./matmul 32 16 2 -1
perf stat -e ref-cycles:u,L1-dcache-loads:u,L1-dcache-load-misses:u,l2_rqsts.references:u,l2_rqsts.miss:u --repeat 20 ./matmul 32 8 4 -1
perf stat -e ref-cycles:u,L1-dcache-loads:u,L1-dcache-load-misses:u,l2_rqsts.references:u,l2_rqsts.miss:u --repeat 20 ./matmul 32 8 2 -1
perf stat -e ref-cycles:u,L1-dcache-loads:u,L1-dcache-load-misses:u,l2_rqsts.references:u,l2_rqsts.miss:u --repeat 20 ./matmul 32 4 2 -1
perf stat -e ref-cycles:u,L1-dcache-loads:u,L1-dcache-load-misses:u,l2_rqsts.references:u,l2_rqsts.miss:u --repeat 20 ./matmul 32 16 8 4
perf stat -e ref-cycles:u,L1-dcache-loads:u,L1-dcache-load-misses:u,l2_rqsts.references:u,l2_rqsts.miss:u --repeat 20 ./matmul 32 16 8 2
perf stat -e ref-cycles:u,L1-dcache-loads:u,L1-dcache-load-misses:u,l2_rqsts.references:u,l2_rqsts.miss:u --repeat 20 ./matmul 32 16 4 2
perf stat -e cycles:u,LLC-load-misses:u,LLC-loads:u,cache-references:u,cache-misses:u ./matmul 32 -1 -1 -1
comment


#python3 parse.py input-512-original output-512-original

# ref-cycles:u
# L1-dcache-loads          
# L1-dcache-load-misses    
# l2_rqsts.references
# l2_rqsts.miss

# LLC-load-misses          
# LLC-loads                
# cache-references:u
# cache-misses:u

 
#IGNORE
# instructions:u
# L1-icache-load-misses    
# L1-dcache-stores         
# fp_arith_inst_retired.scalar_single
# LLC-store-misses         
# LLC-stores
