#!/bin/bash

#SBATCH -J myjob           # Job name
#SBATCH -o %j_o32       # Name of stdout output file
#SBATCH -e %j_e32      # Name of stdout output file
#SBATCH -p skx-normal      # Queue (partition) name
#SBATCH -N 1               # Total # of nodes (must be 1 for serial)
#SBATCH -n 1               # Total # of mpi tasks (should be 1 for serial)
#SBATCH -t 00:30:00        # Run time (hh:mm:ss)
#SBATCH -A CCR21003      # Allocation name (req'd if you have more than 1)

gcc matmul.c -o matmul -O3

perf stat -e ref-cycles:u,L1-dcache-loads:u,L1-dcache-load-misses:u,l2_rqsts.references:u,l2_rqsts.miss:u ./matmul
