#!/bin/bash

#SBATCH -J myjob           # Job name
#SBATCH -o %j_o4096       # Name of stdout output file
#SBATCH -e %j_e4096      # Name of stdout output file
#SBATCH -p skx-normal      # Queue (partition) name
#SBATCH -N 1               # Total # of nodes (must be 1 for serial)
#SBATCH -n 1               # Total # of mpi tasks (should be 1 for serial)
#SBATCH -t 04:30:00        # Run time (hh:mm:ss)
#SBATCH -A CCR21003      # Allocation name (req'd if you have more than 1)

gcc matmul.c -o matmul -O3
perf stat -e cycles:u,instructions:u,cache-references:u,cache-misses:u,L1-dcache-stores:u ./matmul
perf stat -e cycles:u,instructions:u,cache-references:u,cache-misses:u,L1-dcache-loads:u ./matmul
perf stat -e cycles:u,instructions:u,cache-references:u,cache-misses:u,L1-dcache-loads:u ./matmul
perf stat -e cycles:u,instructions:u,cache-references:u,cache-misses:u,L1-dcache-loads:u ./matmul
perf stat -e cycles:u,instructions:u,cache-references:u,cache-misses:u,L1-dcache-loads:u ./matmul
perf stat -e cycles:u,instructions:u,cache-references:u,cache-misses:u,L1-dcache-loads:u ./matmul
perf stat -e cycles:u,instructions:u,cache-references:u,cache-misses:u,L1-dcache-loads:u ./matmul
perf stat -e cycles:u,instructions:u,cache-references:u,cache-misses:u,L1-dcache-loads:u ./matmul
perf stat -e cycles:u,instructions:u,cache-references:u,cache-misses:u,L1-dcache-loads:u ./matmul
perf stat -e cycles:u,instructions:u,cache-references:u,cache-misses:u,L1-dcache-loads:u ./matmul
perf stat -e cycles:u,instructions:u,cache-references:u,cache-misses:u,L1-dcache-loads:u ./matmul
perf stat -e cycles:u,instructions:u,cache-references:u,cache-misses:u,L1-dcache-loads:u ./matmul
perf stat -e cycles:u,instructions:u,cache-references:u,cache-misses:u,L1-dcache-loads:u ./matmul
perf stat -e cycles:u,instructions:u,cache-references:u,cache-misses:u,L1-dcache-loads:u ./matmul
perf stat -e cycles:u,instructions:u,cache-references:u,cache-misses:u,L1-dcache-loads:u ./matmul
perf stat -e cycles:u,instructions:u,cache-references:u,cache-misses:u,L1-dcache-loads:u ./matmul
perf stat -e cycles:u,instructions:u,cache-references:u,cache-misses:u,L1-dcache-loads:u ./matmul
perf stat -e cycles:u,instructions:u,cache-references:u,cache-misses:u,L1-dcache-loads:u ./matmul
perf stat -e cycles:u,instructions:u,cache-references:u,cache-misses:u,L1-dcache-loads:u ./matmul
perf stat -e cycles:u,instructions:u,cache-references:u,cache-misses:u,L1-dcache-loads:u ./matmul


# ref-cycles:u
# L1-dcache-loads          
# L1-dcache-load-misses    
# l2_rqsts.references
# l2_rqsts.miss

# cycles:u
# LLC-load-misses          
# LLC-loads                
# cache-references:u
# cache-misses:u

 
#IGNORE
# instructions:u
# L1-icache-load-misses    
# L1-dcache-stores         
# fp_arith_inst_retired.scalar_single
# LLC-store-misses         
# LLC-stores
