#!/bin/bash

#SBATCH -J myjob           # Job name
#SBATCH -o %j       # Name of stdout output file
#SBATCH -p skx-normal      # Queue (partition) name
#SBATCH -N 1               # Total # of nodes (must be 1 for serial)
#SBATCH -n 1               # Total # of mpi tasks (should be 1 for serial)
#SBATCH -t 01:30:00        # Run time (hh:mm:ss)
#SBATCH -A mmltply      # Allocation name (req'd if you have more than 1)

./myprogram         # Do not use ibrun or any other MPI launcher

